repos:
-   repo: https://github.com/python/black
    rev: ae5588cf073be10b51dc48ad2fc513e11c4f3e03
    hooks:
    -   id: black
        args: [-l 79]
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.2
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    -   id: mypy
        stages: [manual]
-   repo: local
    hooks:
    -   id: commit-check
        name: Check commit message
        stages: [commit-msg, prepare-commit-msg]
        entry: 'bin/check_commit_message.py'
        language: script
