[tool.black]
line-length = 79
target-version = ['py38']
[tool.isort]
line_length=79
force_grid_wrap=0
multi_line_output=3
use_parentheses=true
include_trailing_comma=true
known_third_party=['pytest','setuptools']
